name: 'Read Custom Properties of All Repos in Organization'
description: 'Read all the custom properties and values of all repos in an organization'
author: 'Andrew Brandt <andrew.brandt@hashgraph.com>'
organization: 'PandasWhoCode'
branding:
  icon: 'check-circle'
  color: 'black'

inputs:
  token:
    description: 'Personal Access Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: List all repos in org
      shell: bash
      run: |
        echo "Fetching repos for organization: ${{ inputs.org }}"
        curl -s -H "Authorization: token ${{ inputs.token }}" \
             -H "Accept: application/vnd.github+json" \
             "https://api.github.com/orgs/${{ inputs.org }}/repos?per_page=100" |
        jq -r '.[].full_name' > repo-list.txt
        echo "Repos written to repo-list.txt"
